//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BAS.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nás.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naša škola sa pýši titulom najväčšej plnoorganizovanej základnej umeleckej školy na juhu Banskobystrického kraja, ktorá  metodicky koordinuje školy svojho druhu regiónov: Novohrad, Gemer a Malohont. Je centrom umeleckého vzdelávania v meste Lučenec ....
        /// </summary>
        public static string AboutUsDetailPartialText {
            get {
                return ResourceManager.GetString("AboutUsDetailPartialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naša škola sa pýši titulom najväčšej plnoorganizovanej základnej umeleckej školy na juhu Banskobystrického kraja, ktorá  metodicky koordinuje školy svojho druhu regiónov: Novohrad, Gemer a Malohont.  Pôsobí ako centrum umeleckého vzdelávania v meste Lučenec. Získava významné ocenenia  na domácich  a medzinárodných súťažiach. Úzko spolupracuje so zahraničnými  umeleckými školami EU  a  v rámci  medzinárodných kontaktov úspešne reprezentuje slovenské umenie  na koncertných turné a výtvarných výstavách. Jej ci [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutUsDetailText {
            get {
                return ResourceManager.GetString("AboutUsDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AttemptText {
            get {
                return ResourceManager.GetString("AttemptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novinky.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zisti viac.
        /// </summary>
        public static string btnLearnMore {
            get {
                return ResourceManager.GetString("btnLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viac.
        /// </summary>
        public static string btnMore {
            get {
                return ResourceManager.GetString("btnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odošli.
        /// </summary>
        public static string btnSendText {
            get {
                return ResourceManager.GetString("btnSendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Zriaďovateľ   Súkromnej základnej umeleckej školy, Novohradská 2, 984 01 Lučenec :&lt;/p&gt;
        ///                &lt;p style=&quot;margin-left: 40px&quot;&gt;&lt;b&gt;Základná umelecká škola n.o.&lt;/b&gt;&lt;/p&gt;
        ///            &lt;p&gt;Štatutárny zástupca zriaďovateľa: &lt;b&gt;Mgr. Jana Kemeníková&lt;/b&gt;&lt;/p&gt;
        ///            &lt;p&gt;Správna rada:&lt;ul style=&quot;margin-left: 40px&quot;&gt;&lt;li&gt;predseda: &lt;b&gt;Tomáš Demecs&lt;/b&gt;&lt;/li&gt;
        ///&lt;li&gt;členovia: &lt;b&gt;Ing. Martin Bielik, Kornélia Poprádiová&lt;/b&gt;&lt;/li&gt;                                                 
        ///&lt;/ul&gt;&lt;/p&gt;
        ///&lt;p&gt;Dozorná rada:&lt;ul style=&quot;m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BuildingContentText {
            get {
                return ResourceManager.GetString("BuildingContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zriaďovateľ  školy.
        /// </summary>
        public static string BuildingHeaderText {
            get {
                return ResourceManager.GetString("BuildingHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sídlo školy.
        /// </summary>
        public static string BuildingText {
            get {
                return ResourceManager.GetString("BuildingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktný formulár.
        /// </summary>
        public static string ContactFormText {
            get {
                return ResourceManager.GetString("ContactFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt na školu.
        /// </summary>
        public static string ContactToUsText {
            get {
                return ResourceManager.GetString("ContactToUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet zobrazení: .
        /// </summary>
        public static string CountText {
            get {
                return ResourceManager.GetString("CountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Vzdelanie:
        ///&lt;ul style=&quot;margin-left: 40px&quot;&gt;
        ///&lt;li&gt;1967 – 1973 – Konzervatórium BratislavaAbsolutórium verejným koncertom z tvorby F. Chopina v  Koncertnej sieni Grasalkovicovho paláca v Bratislave&lt;/li&gt;
        ///&lt;li&gt;1996 – 2000 Univerzita Mateja Bela, Banská Bystrica  Fakulta humanitných vied – odbor hudobná pedagogika&lt;/li&gt;
        ///&lt;li&gt;2002 – absolvovanie I. kvalifikacnej skúšky – Metodické centrum Banská Bystrica.&lt;/li&gt;
        ///&lt;li&gt;2012 - ukoncenie funkcného inovacného vzdelávania – Metodické centrum Banská Bystrica.&lt;/li&gt;
        ///&lt;/p&gt;.
        /// </summary>
        public static string CVKemenikText {
            get {
                return ResourceManager.GetString("CVKemenikText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riaditeľstvo.
        /// </summary>
        public static string DirectorateText {
            get {
                return ResourceManager.GetString("DirectorateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string FaxText {
            get {
                return ResourceManager.GetString("FaxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galéria.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanečný odbor rozvíja fyzické a psychické dispozície formou klasického, kreatívneho
        ///a ľudového tanca. Umožňuje vniknúť do oblasti pohybu, rytmického a melodického cítenia,
        ///tempa, dynamiky a taktu. Sústredenosť, precíznosť a disciplína pohybu prináša estetické
        ///výsledky, ktoré sú zamerané na umeleckú fantáziu, prirodzenosť rozvíjania tanečného pohybu
        ///a umeleckú tvorivosť..
        /// </summary>
        public static string HeaderTextDancing {
            get {
                return ResourceManager.GetString("HeaderTextDancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literárno - dramatický odbor sa vyznačuje tvorivou dramatikou osvojením si
        ///dramatických schopností, zručností, a psychofyziologických funkcií. Rozvíja predstavivosť,
        ///fantáziu v improvizáciách a v štrukturovanej dramatickej hre.
        ///LDO zabezepečuje komunikačné schopnosti /verbálne, neverbálne, pohybové/. Dramatická
        ///výchova prináša hodnoty prejavujúce sa v celkovej osobnosti človeka..
        /// </summary>
        public static string HeaderTextLiterary {
            get {
                return ResourceManager.GetString("HeaderTextLiterary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hudobný odbor umožňuje rozvíjať osobnosť, citové zrenie, kultivovanosť
        ///a formovanie charakteru. Vytvára priestor na interpretačné činnosti, ktoré pomocou
        ///umeleckých vedomostí, vlastných predstáv, fantázie a umeleckých zručností pretvára do
        ///vlastnej podoby.
        ///Interpreti vyjadrujú v hudobných dielach svoje pocity a stupeň umeleckého
        ///vyjadrovania. Vnikajú do podstaty umenia a poznávajú krásu prostredníctvom umeleckej
        ///tvorivosti..
        /// </summary>
        public static string HeaderTextMusic {
            get {
                return ResourceManager.GetString("HeaderTextMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výtvarný odbor integruje oblasť citovej a rozumovej výchovy. V harmonickom
        ///vzťahu sa aktivujú všetky zložky osobnosti. Najvyšším cieľom je výchova ku kreativite.
        ///Ťažiskom je individuálny prístup smerovaný k vytváraniu vlastných predstáv, ktoré vyúsťujú
        ///formou zážitkového tvorivého poznávania k vlastnej umeleckej výtvarnej tvorbe..
        /// </summary>
        public static string HeaderTextPainting {
            get {
                return ResourceManager.GetString("HeaderTextPainting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanečný odbor.
        /// </summary>
        public static string HeaderTitleDancing {
            get {
                return ResourceManager.GetString("HeaderTitleDancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literárno-dramatický odbor.
        /// </summary>
        public static string HeaderTitleLiterary {
            get {
                return ResourceManager.GetString("HeaderTitleLiterary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hudobný odbor.
        /// </summary>
        public static string HeaderTitleMusic {
            get {
                return ResourceManager.GetString("HeaderTitleMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výtvarný odbor.
        /// </summary>
        public static string HeaderTitlePainting {
            get {
                return ResourceManager.GetString("HeaderTitlePainting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domov.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úvodná Stránka.
        /// </summary>
        public static string HomePageText {
            get {
                return ResourceManager.GetString("HomePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Údaj je povinný.
        /// </summary>
        public static string IsRequiredText {
            get {
                return ResourceManager.GetString("IsRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text má byť dĺžky {2} až {1} znakov.
        /// </summary>
        public static string LengthText {
            get {
                return ResourceManager.GetString("LengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novohradská 2, 98401 Lučenec.
        /// </summary>
        public static string LogoHeader {
            get {
                return ResourceManager.GetString("LogoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Súkromná základná umelecká škola.
        /// </summary>
        public static string LogoHeaderTitle {
            get {
                return ResourceManager.GetString("LogoHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa.
        /// </summary>
        public static string MessageText {
            get {
                return ResourceManager.GetString("MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naša Poloha.
        /// </summary>
        public static string ourLocationText {
            get {
                return ResourceManager.GetString("ourLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefón.
        /// </summary>
        public static string PhoneText {
            get {
                return ResourceManager.GetString("PhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plagát.
        /// </summary>
        public static string PosterText {
            get {
                return ResourceManager.GetString("PosterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povinný údaj.
        /// </summary>
        public static string RequiredText {
            get {
                return ResourceManager.GetString("RequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjekt.
        /// </summary>
        public static string SubjectText {
            get {
                return ResourceManager.GetString("SubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihlás sa teraz.
        /// </summary>
        public static string textApplyNow {
            get {
                return ResourceManager.GetString("textApplyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zisti viac.
        /// </summary>
        public static string textBtnMore {
            get {
                return ResourceManager.GetString("textBtnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posledné udalosti.
        /// </summary>
        public static string textLatestNew {
            get {
                return ResourceManager.GetString("textLatestNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadchádzajúce udalosti.
        /// </summary>
        public static string textNextEvents {
            get {
                return ResourceManager.GetString("textNextEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string TextUserName {
            get {
                return ResourceManager.GetString("TextUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prečo práve my.
        /// </summary>
        public static string textWhyWe {
            get {
                return ResourceManager.GetString("textWhyWe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máme významné úspechy na medzinárodných a domácich súťažiach a sme najvačšou  plnoorganizovanou  ZUŠ regiónov Novohrad Gemer a Malohont , kde sa žiaci vzdelávajú v hudobnom, výtvarnom, tanečnom a literárno - dramatickom odbore. Na škole posobia profesionálni umeleckí pedagógovia.  Úzko spolupracujeme  s umeleckými školami na Slovensku ( Konzervatórium  Bratislava ) a umeleckými školami Európskej únie ( Francúzsko, Maďarsko , Česká Republika atď) formou vzájomných koncertnych turné , výstavami výtvarných prá [rest of string was truncated]&quot;;.
        /// </summary>
        public static string textWhyWeDetail {
            get {
                return ResourceManager.GetString("textWhyWeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riadiťeľka školy:.
        /// </summary>
        public static string TitleDirector {
            get {
                return ResourceManager.GetString("TitleDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zástupkyňa školy:.
        /// </summary>
        public static string TitleUnderDirector {
            get {
                return ResourceManager.GetString("TitleUnderDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navštívte nás.
        /// </summary>
        public static string VisitUsText {
            get {
                return ResourceManager.GetString("VisitUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stránka.
        /// </summary>
        public static string WebPageText {
            get {
                return ResourceManager.GetString("WebPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zlý formát.
        /// </summary>
        public static string WrongEmailFormatText {
            get {
                return ResourceManager.GetString("WrongEmailFormatText", resourceCulture);
            }
        }
    }
}
