//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAS.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album_t()
        {
            this.File_t = new HashSet<File_t>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> AlbumTypeId { get; set; }
        public int UserId { get; set; }
        public string AlbumPathName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File_t> File_t { get; set; }
    }
}
