//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAS.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class File_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public File_t()
        {
            this.Event_t = new HashSet<Event_t>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string FileName { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsOnTopAlbum { get; set; }
        public bool Private { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> Album_Id { get; set; }
        public int UserId { get; set; }
        public int Sort { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Album_t Album_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event_t> Event_t { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
