//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAS.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message_t()
        {
            this.Message_t1 = new HashSet<Message_t>();
        }
    
        public int Id { get; set; }
        public int New { get; set; }
        public int Deleted { get; set; }
        public Nullable<int> FromUserId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Ip { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message_t> Message_t1 { get; set; }
        public virtual Message_t Message_t2 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
