//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAS.Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class New_t
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string Title { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public string Location { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
